import { Product } from '../types';

export const INITIAL_PRODUCTS: Product[] = [
  // --- Handphone & Gadget ---
  {
    id: "HP01",
    name: "Apple iPhone 15 Pro Max 256GB — Natural Titanium",
    price: 22499000,
    original_price: 24999000,
    img: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=700&q=70",
    images: [
      "https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=700&q=70",
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=700&q=70"
    ],
    tag: "iPhone",
    category: "Handphone & Gadget",
    seller_platform: "Tokopedia",
    seller_name: "iBox Official Store",
    location: "Jakarta Pusat",
    rating: 5.0,
    sold_count: 8900,
    sizes: ["256GB", "512GB", "1TB"],
    colors: ["Natural Titanium", "Black Titanium", "Blue Titanium"],
    description: "Garansi Resmi iBox Indonesia 1 Tahun. Chipset A17 Pro dengan bodi titanium aerospace-grade dan tombol Action Button.",
    sizes_cm: "Varian Memori:\n- 256GB Internal RAM 8GB\n- 512GB Internal RAM 8GB\n- 1TB Internal RAM 8GB",
    shipping_methods: ["Bebas Ongkir Tokopedia", "Gojek Instant", "JNE YES Plus Asuransi"],
    stock: 15
  },
  {
    id: "HP02",
    name: "Samsung Galaxy S24 Ultra 5G 12/512GB — Titanium Gray",
    price: 20999000,
    original_price: 21999000,
    img: "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=700&q=70",
    tag: "Samsung",
    category: "Handphone & Gadget",
    seller_platform: "Shopee",
    seller_name: "Samsung Official Shop",
    location: "Jakarta Selatan",
    rating: 4.9,
    sold_count: 6400,
    sizes: ["12/256GB", "12/512GB", "12/1TB"],
    colors: ["Titanium Gray", "Titanium Black", "Titanium Violet"],
    description: "Diperkuat Galaxy AI, Kamera 200MP Zoom 100x ProVisual Engine, dan S-Pen terintegrasi.",
    sizes_cm: "Layar: 6.8 inch Dynamic AMOLED 2X 120Hz Quad HD+\nBaterai: 5000 mAh Fast Charge 45W",
    shipping_methods: ["Shopee Xpress Instant", "SiCepat REG"],
    stock: 20
  },
  {
    id: "HP03",
    name: "TWS Sony WF-1000XM5 Noise Canceling Wireless Earbuds",
    price: 3999000,
    original_price: 4599000,
    img: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=700&q=70",
    tag: "TWS",
    category: "Handphone & Gadget",
    seller_platform: "Tokopedia",
    seller_name: "Sony Audio Official Store",
    location: "Jakarta Barat",
    rating: 4.9,
    sold_count: 3120,
    sizes: ["Standard Fit"],
    colors: ["Black", "Silver Platinum"],
    description: "Noise canceling terbaik kelas dunia dengan driver Dynamic Driver X 8.4mm dan sertifikasi Hi-Res Wireless Audio LDAC.",
    sizes_cm: "Berat earbud: 5.9 gram per earbud\nDaya tahan baterai: 8 jam + 16 jam case total 24 jam",
    shipping_methods: ["Tokopedia Instant", "Anteraja"],
    stock: 35
  },

  // --- Elektronik & TV ---
  {
    id: "EL01",
    name: "LG 55 Inch 4K UHD Smart TV Thin Q AI 55UT8000",
    price: 7299000,
    original_price: 8999000,
    img: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=700&q=70",
    tag: "Smart TV",
    category: "Elektronik & TV",
    seller_platform: "Tokopedia",
    seller_name: "LG Electronics Official",
    location: "Tangerang",
    rating: 4.9,
    sold_count: 2450,
    sizes: ["43 Inch", "50 Inch", "55 Inch", "65 Inch"],
    colors: ["Dark Titan Gray"],
    description: "Prosesor α5 AI Processor 4K Gen7, webOS 24 dengan Magic Remote voice control & HDR10 Pro.",
    sizes_cm: "Dimensi dengan kaki: 1235 x 780 x 230 mm\nBerat: 14.2 kg",
    shipping_methods: ["Kargo Kurir Toko", "J&T Cargo"],
    stock: 12
  },
  {
    id: "EL02",
    name: "AC Sharp 1/2 PK Inverter Plasmacluster AH-X6ZY",
    price: 3699000,
    original_price: 4299000,
    img: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=700&q=70",
    tag: "AC",
    category: "Elektronik & TV",
    seller_platform: "Shopee",
    seller_name: "Sharp Electronics Shop",
    location: "Jakarta Barat",
    rating: 4.8,
    sold_count: 1890,
    sizes: ["0.5 PK", "1 PK", "1.5 PK"],
    colors: ["Pure White"],
    description: "Hemat listrik hingga 65% dengan teknologi J-Tech Inverter dan pemurni udara Plasmacluster HD 7000.",
    sizes_cm: "Kapasitas Dingin: 5000 BTU/h\nKonsumsi Daya: 360 Watt Eco Mode",
    shipping_methods: ["Kurir Toko + Jasa Pasang"],
    stock: 18
  },

  // --- Otomotif & Aksesoris Motor ---
  {
    id: "OT01",
    name: "Helm Full Face KYT TT Course Black Matt — Original SNI / DOT",
    price: 1150000,
    original_price: 1350000,
    img: "https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=700&q=70",
    tag: "Helm",
    category: "Otomotif & Aksesoris Motor",
    seller_platform: "Tokopedia",
    seller_name: "KYT Helmet Official",
    location: "Bandung",
    rating: 4.9,
    sold_count: 5200,
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Black Matt", "Flat White", "Red Fluo"],
    description: "Helm full face aerodinamis berbahan ADT-Advanced Thermo Plastic dengan visor flat tear-off ready & slot intercom.",
    sizes_cm: "M: Lingkar kepala 57-58 cm\nL: Lingkar kepala 59-60 cm\nXL: Lingkar kepala 61-62 cm",
    shipping_methods: ["Bebas Ongkir Tokopedia", "JNE Reguler Bubble Wrap"],
    stock: 40
  },
  {
    id: "OT02",
    name: "Intercom Helm FreedConn T-MAX S Pro Group Mesh Communication",
    price: 780000,
    original_price: 950000,
    img: "https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=700&q=70",
    tag: "Intercom",
    category: "Otomotif & Aksesoris Motor",
    seller_platform: "Shopee",
    seller_name: "MotoGadget Store",
    location: "Jakarta Timur",
    rating: 4.9,
    sold_count: 3400,
    sizes: ["Single Pack", "Dual Pack"],
    colors: ["Matte Black"],
    description: "Intercom Bluetooth 5.1 anti air IP65 untuk komunikasi touring hingga 6 rider bersamaan jangkauan 1200m.",
    sizes_cm: "Baterai: 570mAh (Standby 300 jam, Bicara 15 jam)\nPengisian daya Type-C Fast Charging",
    shipping_methods: ["Shopee Xpress", "J&T Express"],
    stock: 25
  },
  {
    id: "OT03",
    name: "Oli Mesin Motul 7100 4T 10W-40 100% Ester Synthetic 1 Liter",
    price: 215000,
    original_price: 260000,
    img: "https://images.unsplash.com/photo-1486006920555-c77dce18193b?auto=format&fit=crop&w=700&q=70",
    tag: "Oli Mesin",
    category: "Otomotif & Aksesoris Motor",
    seller_platform: "Tokopedia",
    seller_name: "Motul Official Store",
    location: "Surabaya",
    rating: 5.0,
    sold_count: 12400,
    sizes: ["1 Liter", "0.8 Liter"],
    colors: ["Red Fluid Ester"],
    description: "Oli mesin balap dan harian 100% Synthetic Ester standar API SN / JASO MA2 untuk perlindungan suhu ekstrem.",
    sizes_cm: "Volume: 1000 ml Botol Segel Hologram",
    shipping_methods: ["Tokopedia Instant", "J&T Cargo"],
    stock: 100
  },
  {
    id: "OT04",
    name: "Sarung Tangan Motor Full Finger Leather Touring Gloves",
    price: 185000,
    original_price: 240000,
    img: "https://images.unsplash.com/photo-1609630875171-b1321377ee65?auto=format&fit=crop&w=700&q=70",
    tag: "Sarung Tangan",
    category: "Otomotif & Aksesoris Motor",
    seller_platform: "Shopee",
    seller_name: "RiderZone Gear",
    location: "Yogyakarta",
    rating: 4.8,
    sold_count: 2800,
    sizes: ["M", "L", "XL"],
    colors: ["Stealth Black", "Carbon Yellow"],
    description: "Sarung tangan motor kulit kombinasi protector batok carbon di bagian buku jari. Kompatibel layar sentuh HP.",
    sizes_cm: "M: Lebar telapak 8-8.5 cm\nL: Lebar telapak 8.5-9 cm\nXL: Lebar telapak 9-9.5 cm",
    shipping_methods: ["Shopee Hemat", "SiCepat REG"],
    stock: 30
  },

  // --- Komputer & Gaming ---
  {
    id: "KM01_G",
    name: "Sony PlayStation 5 PS5 Slim Disc Edition Garansi Resmi",
    price: 8999000,
    original_price: 9699000,
    img: "https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&w=700&q=70",
    tag: "Console",
    category: "Komputer & Gaming",
    seller_platform: "Tokopedia",
    seller_name: "PlayStation Authorized Dealer",
    location: "Jakarta Selatan",
    rating: 5.0,
    sold_count: 4120,
    sizes: ["Disc Edition 1TB", "Digital Edition 1TB"],
    colors: ["Classic White"],
    description: "Versi Slim 30% lebih ringkas dengan SSD 1TB ultra-fast speed, DualSense controller haptic feedback.",
    sizes_cm: "Kapasitas SSD: 1TB Custom NVMe\nVideo Output: 4K 120Hz & 8K HDR Ready",
    shipping_methods: ["Gojek Instant", "JNE YES Asuransi"],
    stock: 10
  },
  {
    id: "KM02_G",
    name: "Mechanical Keyboard Wireless Gaming RGB HOT-SWAP 75%",
    price: 649000,
    original_price: 850000,
    img: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=700&q=70",
    tag: "Keyboard",
    category: "Komputer & Gaming",
    seller_platform: "Shopee",
    seller_name: "TechKey Central",
    location: "Tangerang",
    rating: 4.9,
    sold_count: 6200,
    sizes: ["Red Switch", "Brown Switch", "Yellow Linear"],
    colors: ["Retro Grey", "Chalk White"],
    description: "Keyboard 3-mode koneksi (Bluetooth 5.0, 2.4GHz Wireless, Type-C). Gasket mount empuk dengan sound dampening foam.",
    sizes_cm: "Layout: 75% 82-Keys + Volume Knob Metalik\nBaterai: 4000mAh Rechargable",
    shipping_methods: ["Shopee Express", "J&T Express"],
    stock: 45
  },

  // --- T-Shirt & Streetwear Fashion ---
  {
    id: "TS01",
    name: "NEXUS Heavyweight Oversized Tee — Ink Black",
    price: 189000,
    original_price: 249000,
    img: "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=700&q=70",
    images: [
      "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=700&q=70",
      "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=700&q=70"
    ],
    tag: "Tee",
    category: "T-Shirt & Kaos",
    seller_platform: "Tokopedia",
    seller_name: "NEXUS Official Store",
    location: "Jakarta Selatan",
    rating: 4.9,
    sold_count: 3420,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Ink Black", "Chalk White", "Olive Drab"],
    description: "Kaos unisex berbahan Heavyweight Cotton Combed 24s gramasi 240gsm. Potongan relaxed boxy drop shoulder khas streetwear.",
    sizes_cm: "S: Lebar 52cm, Panjang 70cm\nM: Lebar 55cm, Panjang 73cm\nL: Lebar 58cm, Panjang 76cm\nXL: Lebar 61cm, Panjang 78cm\nXXL: Lebar 64cm, Panjang 80cm",
    shipping_methods: ["Bebas Ongkir Tokopedia", "JNE Reguler", "Gojek Instant"],
    stock: 45
  },
  {
    id: "HD01",
    name: "NEXUS Heavy Fleece Hoodie — Volt Backprint",
    price: 449000,
    original_price: 599000,
    img: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=700&q=70",
    tag: "Hoodie",
    category: "Hoodie & Outerwear",
    seller_platform: "Tokopedia",
    seller_name: "NEXUS Official Store",
    location: "Jakarta Selatan",
    rating: 5.0,
    sold_count: 1540,
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Jet Black", "Volt Yellow"],
    description: "400gsm French Terry fleece tebal berserat lembut. Kupluk ganda dan kantong kangguru depan.",
    sizes_cm: "S: Lebar 56cm, Panjang 68cm\nM: Lebar 59cm, Panjang 71cm\nL: Lebar 62cm, Panjang 74cm\nXL: Lebar 65cm, Panjang 77cm",
    shipping_methods: ["Bebas Ongkir", "JNE YES"],
    stock: 22
  },
  {
    id: "CL01",
    name: "Baggy Loose Rigid Denim Pants — Stone Wash",
    price: 529000,
    original_price: 690000,
    img: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?auto=format&fit=crop&w=700&q=70",
    tag: "Denim",
    category: "Celana & Denim",
    seller_platform: "Tokopedia",
    seller_name: "NEXUS Official Store",
    location: "Jakarta Selatan",
    rating: 4.9,
    sold_count: 2310,
    sizes: ["28", "30", "32", "34", "36"],
    colors: ["Stone Wash Blue", "Deep Indigo"],
    description: "Celana jeans 14oz non-stretch potongan sangat lebar (baggy wide leg) dengan efek cucian vintage.",
    sizes_cm: "28: Pinggang 76cm, Panjang 102cm\n30: Pinggang 81cm, Panjang 104cm\n32: Pinggang 86cm, Panjang 106cm\n34: Pinggang 91cm, Panjang 108cm",
    shipping_methods: ["Bebas Ongkir", "JNE Reguler"],
    stock: 25
  },
  {
    id: "SP01",
    name: "High Top Canvas Skate Sneaker — Mono Black",
    price: 459000,
    original_price: 599000,
    img: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=700&q=70",
    tag: "Sneakers",
    category: "Sepatu & Sneakers",
    seller_platform: "Tokopedia",
    seller_name: "Footwear Garage",
    location: "Bandung",
    rating: 4.9,
    sold_count: 1920,
    sizes: ["39", "40", "41", "42", "43", "44"],
    colors: ["Mono Black", "Classic White"],
    description: "Sepatu skate tinggi berbahan kanvas 12oz dengan sol vulkanisir cengkraman tinggi.",
    sizes_cm: "39: 25.0cm\n40: 25.5cm\n41: 26.5cm\n42: 27.0cm\n43: 28.0cm\n44: 28.5cm",
    shipping_methods: ["Bebas Ongkir", "JNE YES"],
    stock: 18
  },

  // --- Rumah Tangga & Kecantikan ---
  {
    id: "RT01",
    name: "Aroma Diffuser Ultrasonic Humidifier 500ml + Essential Oil",
    price: 149000,
    original_price: 210000,
    img: "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=700&q=70",
    tag: "Diffuser",
    category: "Rumah Tangga & Dapur",
    seller_platform: "Shopee",
    seller_name: "HomeAroma Shop",
    location: "Semarang",
    rating: 4.9,
    sold_count: 15200,
    sizes: ["500ml Standard"],
    colors: ["Wood Grain Dark", "White Pure"],
    description: "Humidifier ultrasonic dengan 7 lampu LED warna-warni dan timer otomatis 1H/3H/6H.",
    sizes_cm: "Kapasitas Tangki: 500 ml air\nBonus 2 botol essential oil Lavender & Peppermint",
    shipping_methods: ["Shopee Xpress", "Anteraja"],
    stock: 50
  },
  {
    id: "KC01",
    name: "Sunscreen Gel SPF 50 PA++++ Hydrating UV Protection 50ml",
    price: 65000,
    original_price: 85000,
    img: "https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=700&q=70",
    tag: "Skincare",
    category: "Kecantikan & Kesehatan",
    seller_platform: "Tokopedia",
    seller_name: "GlowBeauty Official",
    location: "Jakarta Selatan",
    rating: 4.9,
    sold_count: 28900,
    sizes: ["50ml Tube"],
    colors: ["Clear Gel"],
    description: "Sunscreen tekstur gel dingin tanpa whitecast, cepat meresap dan aman untuk kulit sensitif jerawat.",
    sizes_cm: "Netto: 50 ml BPOM Registered",
    shipping_methods: ["Tokopedia Instant", "J&T Express"],
    stock: 120
  }
];
